export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const PRODUCTS_RECEIVE = "PRODUCTS_RECEIVE";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_RECEIVE = "PRODUCT_DETAILS_RECEIVE";

